
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./provider";
import Footer from "./components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
      <html lang="en">
        <body
         
        >
           <Providers>
          <Navbar />

          {children}
          <Footer />
          </Providers>
        </body>
      </html>
    
  );
}
